#  To run: docker-compose -f docker-compose.local.yml up --build
version: '3'

services:
  storagesvc:
    build:
      context: .
      dockerfile: DockerfileLocal
    ports:
      - "50030:50030"
      - "50035:50035"
    env_file:
      - .env