version: '3'

networks:
  my_network:
    external: true
    driver: bridge

services:
  db:
    image: postgres:16.2-alpine3.19
    container_name: storagesvc_postgres_db
    env_file:
      - .env
    volumes:
      - ./src/main/resources/initdb/init1-storagesvcdb-schema.sql:/docker-entrypoint-initdb.d/init1-storagesvcdb-schema.sql
      - ./src/main/resources/initdb/init2-storagesvcdb-data.sql:/docker-entrypoint-initdb.d/init2-storagesvcdb-data.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  storagesvc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50030:50030"
      - "50035:50035"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - my_network

volumes:
  postgres_data: